Assets/Actors/Animations.meta
Assets/Actors/Models.meta
Assets/Actors/Sound.meta
Assets/Objects/Animations.meta
Assets/Objects/Props/WallLamp/Materials.meta
Assets/Objects/Props/WallLamp/Materials/lambert1.mat
Assets/Objects/Props/WallLamp/Materials/lambert1.mat.meta
Assets/Scenes/Debug/Test environment.unity
Assets/Scripts/Actors.meta
Assets/Scripts/Effects.meta
Assets/Scripts/ItemTriggerCheck.cs
Assets/Scripts/ItemTriggerCheck.cs.meta
Assets/Scripts/Managers.meta
Assets/Scripts/Objects.meta
Assets/Scripts/Sound.meta
Assets/Scripts/StoryboardProgression.cs
Assets/Scripts/StoryboardProgression.cs.meta

Temporary scripts that needs to be worked on later.

Item placement check and Scene changer for storyboard

---

Assets/Scenes/Debug/Corridors.unity
Assets/Scenes/Debug/Test environment.unity
Assets/Scripts/Actors/Character_Move.cs

Added crouch. Added MouseLook by Alex and refined movement with Alex.

Crouch, look, move.

---

Assets/Scripts/GlowScripts/HaloScript.cs
Assets/Scripts/GlowScripts/Raycaster.cs

RayCaster skall läggas på MainCamera. HaloScript läggs på ALLA de saker
man skall kunna plocka upp. De sakerna måste även få Halo tillagt då det
inte är scriptbart

Glowe-Effekt

---

Assets/Art_assets/Prefabs/System.meta
Assets/Art_assets/Prefabs/System/Player.prefab
Assets/Art_assets/Prefabs/System/Player.prefab.meta
Assets/Art_assets/Prefabs/System/StateManager.prefab
Assets/Art_assets/Prefabs/System/StateManager.prefab.meta
Assets/Scenes/Debug/Test environment.unity
Assets/Scripts/Statemachine.meta
Assets/Scripts/Statemachine/CreditsState.cs
Assets/Scripts/Statemachine/CreditsState.cs.meta
Assets/Scripts/Statemachine/IGameState.cs
Assets/Scripts/Statemachine/IGameState.cs.meta
Assets/Scripts/Statemachine/PauseState.cs
Assets/Scripts/Statemachine/PauseState.cs.meta
Assets/Scripts/Statemachine/PlayState.cs
Assets/Scripts/Statemachine/PlayState.cs.meta
Assets/Scripts/Statemachine/StartState.cs
Assets/Scripts/Statemachine/StartState.cs.meta
Assets/Scripts/Statemachine/StateManager.cs
Assets/Scripts/Statemachine/StateManager.cs.meta

closes #10 
- Statemanager
- Statemanager interface
- Start, Pause, Credits and Play state
- Player prefab

Statemachine

---

Assets/Scenes/startScreen.unity
Assets/Scripts/startMenuScript.cs

Credits meny, placeholder namn

---

Assets/Art_assets/Textures/Materials/mat_cleaning_closet.mat
Assets/Art_assets/Textures/nrm_cleaning_closet.tga.meta
Assets/Art_assets/Textures/txt_cleaning_closet.tga.meta

- Added Cleaning closet texture
- Added Cleaning closet normal map

Cleaning Closet Textures

---

Assets/Art_assets/Textures/MAT_cabinroof.mat
Assets/Art_assets/Textures/Materials/colRedSG1.mat
Assets/Art_assets/Textures/Materials/mat_broom.mat
Assets/Art_assets/Textures/Materials/mat_bucket.mat
Assets/Art_assets/Textures/Materials/mat_bureau.mat
Assets/Art_assets/Textures/mat_walllamp.mat
Assets/Scenes/Debug/Patriks_prefab_zone/patriks_prefab_zone.unity

Fixed Cabin roof textures

---

Assets/Actors.meta
Assets/Scenes/Preliminary.unity
Assets/Scripts/DoorInteraction.cs
Assets/Scripts/DoorInteraction.cs.meta
Assets/Scripts/DoorScript.cs
Assets/Scripts/DoorScript.cs.meta
Assets/Scripts/pauseMenuScript.cs
Assets/Scripts/startMenuScript.cs

DoorInteraction script, Door Script

DoorInteraction

---

Assets/Prefabs/Environments/Rum/Cabin_Wright.prefab
Assets/Scenes/Debug/MarcusOverengenWrightRoom.unity
Assets/Scenes/Debug/MarcusOverengenWrightRoom.unity.meta

WrightsRumInrett

---

Assets/Prefabs/Environments/Rum/Cabin_Erin.prefab
Assets/Scenes/Debug/51-myChild.unity
Assets/Scenes/Debug/51-myChild.unity.meta

closes #51 
gjorde Eris rum, props och ljus

51 mychild

---

Assets/Prefabs/Environments/Rum/Ballroom_Empty.prefab
Assets/Scenes/Debug/MarcusOverengenBalrumInredning.unity
Assets/Scenes/Debug/MarcusOverengenBalrumInredning.unity.meta

closes #54
Ballrummet dekorerat, fattas bara några glas och möjlig omplacering av
glas och diverse mat tillbehör. Detta för att de är för små för att
kunna arbetas med.

BallrumDekoreratNästanKlar

---

Assets/Prefabs/Environments/Rum/Cigarrum.prefab
Assets/Scenes/Debug/57-MyFourthChild.unity
Assets/Scenes/Debug/57-MyFourthChild.unity.meta

#57 Ser mer ut som cigarrum. Det saknas lite saker i mitten av rummet, men det får dugga för vertical slice

57-Cigarrum

---

Assets/Prefabs/Environments/Rum/Cabin_Gambling.prefab
Assets/Scenes/Debug/58-MyFifthChild.unity
Assets/Scenes/Debug/58-MyFifthChild.unity.meta

58-gambling

---

Assets/Prefabs/Environments/Rum/PREFAB_Garderob.prefab
Assets/Scenes/Debug/JohnsGarderob.unity
Assets/Scenes/Debug/JohnsGarderob.unity.meta

Fixat conflikt

---

Assets/Prefabs/Environments/Rum/Cabin_Erin.prefab
Assets/Scenes/Debug/Max2.unity
Assets/Scripts/ErinStory.cs
Assets/Scripts/ErinStory.cs.meta
Assets/Scripts/PickUpObject.cs

Requires giving a bottle to Erin now.

Finished ErinStory

---

Assets/Actors.meta
Assets/Prefabs/Canvas.meta
Assets/Prefabs/Canvas/PauseMenuCanvas.prefab
Assets/Prefabs/Canvas/PauseMenuCanvas.prefab.meta
Assets/Prefabs/System/EventSystem.prefab
Assets/Prefabs/System/EventSystem.prefab.meta
Assets/Scenes/Debug/FredrikWrightStoryRoom.unity
Assets/Scenes/Debug/FredrikWrightStoryRoom.unity.meta
Assets/Scripts/PickUpObject.cs
ProjectSettings/TagManager.asset

Debug scene, lägt in scripts på prefabs, fixat toss och rotation på
pickup, lagt till tagen Door för dörren.

Enviroment And debug scene

---

Assets/59-Städskrubb.unity
Assets/59-Städskrubb.unity.meta
Assets/Prefabs/Environments/Rum/sm_cleaning_closet.prefab

Städskrubb klar.

---

Assets/MarcusOverengen_ResizingAllRoomProps.unity
Assets/MarcusOverengen_ResizingAllRoomProps.unity.meta
Assets/Prefabs/Environments/Rum/Ballroom_Empty.prefab
Assets/Prefabs/Environments/Rum/Cabin_Big.prefab
Assets/Prefabs/Environments/Rum/Cabin_Erin.prefab
Assets/Prefabs/Environments/Rum/Cabin_Gambling.prefab
Assets/Prefabs/Environments/Rum/Cabin_Wright.prefab
Assets/Prefabs/Environments/Rum/Cigarrum.prefab
Assets/Prefabs/Environments/Rum/PREFAB_Garderob.prefab

Alla props i rummen är i ratt strorlek =)

ReSeizeingAllRoomProps

---

Assets/Scenes/Day 1.unity
Assets/Scenes/Preliminary.unity

Fixed Flickering In Day One And Preliminary

---

Assets/Prefabs/Environments/Rum/CigarrumKLAR.prefab
Assets/Prefabs/Environments/Rum/CigarrumKLAR.prefab.meta
Assets/Prefabs/Props/PREFAB_Beer.prefab
Assets/Prefabs/Props/PREFAB_Beer.prefab.meta
Assets/Prefabs/Props/SM_cabinwall_door.prefab
Assets/Prefabs/Props/SM_cabinwall_door.prefab.meta
Assets/Scenes/Debug/50-CigarRoom-Fredrik.unity
Assets/Scenes/Debug/50-CigarRoom-Fredrik.unity.meta

#50 - Cigarrum klart

---

Assets/Prefabs/Character.prefab
Assets/Prefabs/Environments/Korridorer/Corridor_Straight_Door.prefab
Assets/Prefabs/Props/Prefab_Winebottle.prefab
Assets/Prefabs/Props/Prefab_fork.prefab

Sista ändringar

---

Assets/Scenes/Day 1.unity

Lagt till karaktarakeerer i day one

Lagt till karaktarer i day One
